### ISSUE TITLE
[bun-utilities] new bindings

### ISSUE THREAD

**Issue by xhyrom** [bluwy/bun-vite-ts-test#1]
![image](https://user-images.githubusercontent.com/56601352/179342220-255858e5-63e8-4d9b-9d51-b90823797f42.png)

I think you can update https://github.com/bluwy/bun-vite-ts-test#notes :D

[released](https://github.com/xHyroM/bun-utilities/runs/7368702401?check_suite_focus=true)

**Comment by xhyrom** [comment]
also:
https://github.com/bluwy/bun-vite-ts-test/blob/13cd6b93b9e8b892712cfd8866321eece6361d45/patches_temp/esbuild%2B0.14.48.patch#L63
here you should use
```js
child_process.exec([ command, args.concat(`--service=${"0.14.48"}`) ])
child_process.spawn(command, args.concat(`--service=${"0.14.48"}`) )
```

**PS:** exec is alias for `spawn` but accepts command and args in one array like `Deno.exec()`

cc @bluwy

**Comment by bluwy** [comment]
Thanks for the hint! I updated it, but it looks like bun panicked when running it somehow. Got a cryptic error:
```
error when starting dev server:
@/Users/bjorn/Work/playground/bun-vite-ts/node_modules/vite/dist/node/chunks/dep-561c5231.js:36190:24
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```
when applying the esbuild patch (doesn't happen if not applying esbuild patch). The file it points to is to a random code location.

Anyways we could keep this issue alive if you'd like to keep the discussion going, or close otherwise 🙂
